# Generated by Django 4.2.16 on 2024-11-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone')),
                ('file_number', models.CharField(max_length=255, verbose_name='file number')),
                ('student_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='student number')),
            ],
            options={
                'unique_together': {('name', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('specialization', models.CharField(help_text='doctor specialization', max_length=255, verbose_name='specialization')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone')),
            ],
            options={
                'unique_together': {('name', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='appointment date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.patient')),
            ],
        ),
    ]
