# Generated by Django 4.2.16 on 2024-11-17 17:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='appointment date'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient', 'appointment_date')},
        ),
    ]
