# Generated by Django 4.2.16 on 2024-11-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_specialty_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
