# Generated by Django 4.2.20 on 2025-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
    ]
