# Generated by Django 4.2.20 on 2025-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_patient_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='is canceled'),
        ),
    ]
