# Generated by Django 4.2.20 on 2025-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=255, verbose_name='appointment type')),
                ('cost', models.BigIntegerField(verbose_name='cost')),
            ],
            options={
                'verbose_name': 'appointment cost',
                'verbose_name_plural': 'appointment costs',
            },
        ),
    ]
