# Generated by Django 4.2.20 on 2025-03-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_is_paid'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'debts',
                'verbose_name_plural': 'debts',
            },
        ),
        migrations.DeleteModel(
            name='AppointmentCost',
        ),
    ]
