# Generated by Django 4.2.20 on 2025-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_debts_delete_appointmentcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Appointment Cost',
                'verbose_name_plural': 'Appointment Costs',
            },
        ),
    ]
