# Generated by Django 4.2.20 on 2025-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_appointmentcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcost',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='price'),
        ),
    ]
